name: maple
description: A home automation smart application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.3
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  dotted_border: ^2.0.0+2
  sliding_up_panel: ^2.0.0+1
  sleek_circular_slider: ^2.0.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  flutter_screenutil: ^5.3.1
  flutter_login: ^3.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+11
  table_calendar: ^3.0.4
  bottom_bar_with_sheet: ^2.3.1
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.3
  #flutter_lints: ^1.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_1024.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/icons/svg/
    - assets/icons/menu_icons/

  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700

    - family: "ABeeZee"
      fonts:
        - asset: "assets/fonts/ABeeZee-Italic.ttf"
          style: "italic"
        - asset: "assets/fonts/ABeeZee-Regular.ttf"
          style: "normal"

    - family: "Lexend"
      fonts:
        - asset: "assets/fonts/Lexend-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Lexend-ExtraLight.ttf"
          weight: 200